name: bhyvemgr test

on:
  push:
    paths-ignore:
      - '**/LICENSE'
      - '**/README.md'
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: bhyvemgr testing on FreeBSD VM
      id: test
      uses: vmactions/freebsd-vm@v1.2.1
      with:
        release: "15.0"
        usesh: true
        prepare: |
          export IGNORE_OSVERSION=yes
          pkg update -f
          pkg install -y lazarus-qt6

        run: |
          set -e -x
          chmod +x build.sh
           ./build.sh release qt6
          pkg remove -y lazarus-qt6
          pkg install -y lazarus-qt5
          ./build.sh release qt5
          pkg remove -y lazarus-qt5
          pkg install -y lazarus-gtk2
          ./build.sh release gtk2
